export type RestaurantRoomRow = {
  id: number;
  restaurant_name: string;
  room_name: string;
  restaurant_des: string | null;
  room_desc: string | null;
  address: string | null;
  event_type: string | null;
  lat: number | null;
  lng: number | null;
  time: string | null;
  seated_capacity: number | null;
  standing_capacity: number | null;
  privacy_level: string | null;
  noise_level: string | null;
  primary_vibe: string | null;
  vibe_tags: string | null;
  a_v: string | null;
  min_spend_estimate: number | null;
  menu_link: string | null;
  google_place_id: string | null;
  yelp_business_id: string | null;
  contact_email: string | null;
  response_time_notes: string | null;
  room_photo_link: string | null;
  tax_structure: string | null;
  service_charge_gratuity: string | null;
  cake_fee: string | null;
  corkage_fee: string | null;
  cancellation_policy: string | null;
  deposit_required: string | null;
  payment_terms: string | null;
  notes: string | null;
};
